/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Media = {
  _id: string;
  _type: "media";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  type: "photo" | "video" | "url";
  imageFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  videoUrl?: string;
  externalUrl?: string;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Events = {
  _id: string;
  _type: "events";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventTitle?: LocaleString;
  slug: Slug;
  eventDescription?: LocaleBlockContent;
  date: string;
  time?: string;
  location?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "location";
  };
  media?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "media";
  }>;
  tags: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "tag";
  }>;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  place: string;
  address: string;
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  pl?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ua?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type LocaleString = {
  _type: "localeString";
  en?: string;
  pl?: string;
  ua?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | Geopoint | Media | SanityFileAsset | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Events | Location | LocaleBlockContent | Slug | LocaleString | Tag;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: galleryPhotosQuery
// Query: *[_type == "media" && type == "photo" && defined(imageFile.asset)] {      "image": {      "id": _id,  "alt": title,  "url": imageFile.asset->url,  "lqip": imageFile.asset->metadata.lqip,  "dimensions": imageFile.asset->metadata.dimensions  }  }
export type GalleryPhotosQueryResult = Array<{
  image: {
    id: string;
    alt: string;
    url: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  };
}>;
// Variable: futureEventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date >= now()] {      "id": _id,  "title": eventTitle[$locale],  date,  time,    "location": location->{    place,    address,  }  }
export type FutureEventsQueryResult = Array<{
  id: string;
  title: Array<{
    _type: "localeString";
    en?: string;
    pl?: string;
    ua?: string;
  }> | null;
  date: string;
  time: string | null;
  location: {
    place: string;
    address: string;
  } | null;
}>;
// Variable: pastEventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date < now()] | order(date desc) {      "id": _id,  "title": eventTitle[$locale],  date,  time,    "location": location->{    place,    address,  }  }
export type PastEventsQueryResult = Array<{
  id: string;
  title: Array<{
    _type: "localeString";
    en?: string;
    pl?: string;
    ua?: string;
  }> | null;
  date: string;
  time: string | null;
  location: {
    place: string;
    address: string;
  } | null;
}>;
// Variable: galleryPhotosCountQuery
// Query: count(*[_type == "media" && type == "photo" && defined(imageFile.asset)])
export type GalleryPhotosCountQueryResult = number;
// Variable: majorEventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "major"]._id)] | order(date asc) {  "id": _id,  "title": eventTitle[$locale],  date,  "media": media[]->{    ...select(type == 'photo' => {        "image": {      "id": _id,  "alt": title,  "url": imageFile.asset->url,  "lqip": imageFile.asset->metadata.lqip,  "dimensions": imageFile.asset->metadata.dimensions  }    })  },  }
export type MajorEventsQueryResult = Array<{
  id: string;
  title: Array<{
    _type: "localeString";
    en?: string;
    pl?: string;
    ua?: string;
  }> | null;
  date: string;
  media: Array<{
    image: {
      id: string;
      alt: string;
      url: string | null;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    };
  }> | null;
}>;
// Variable: minorEventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "minor" || name == "major"]._id)] | order(date asc) {  "id": _id,  "description": eventDescription[$locale],  date,  "media": media[]->{    ...select(type == 'photo' => {        "image": {      "id": _id,  "alt": title,  "url": imageFile.asset->url,  "lqip": imageFile.asset->metadata.lqip,  "dimensions": imageFile.asset->metadata.dimensions  }    }),    ...select(type == 'video' => {        "video": {    "id": _id,    "alt": title,    "url": coalesce(videoUrl, videoFile.asset->url, externalUrl)  }    })  },  }
export type MinorEventsQueryResult = Array<{
  id: string;
  description: Array<{
    _type: "localeBlockContent";
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    pl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    ua?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }> | null;
  date: string;
  media: Array<{
    image: {
      id: string;
      alt: string;
      url: string | null;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    };
    video: {
      id: string;
      alt: string;
      url: string | null;
    };
  }> | null;
}>;
// Variable: majorEventsYearsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "major"]._id)] | order(date asc) {    date  }
export type MajorEventsYearsQueryResult = Array<{
  date: string;
}>;
// Variable: eventsCountQuery
// Query: count(*[_type == "events" && references(*[_type == "tag" && (name == "major" || name == "minor")]._id)])
export type EventsCountQueryResult = number;
// Variable: eventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && (name == "major" || name == "minor")]._id)]  | order(date desc) [$start...$end] {    "id": _id,    "title": eventTitle[$locale],    slug,    date,    "tags": tags[]->{      "id": _id,      name    },    "media": media[0]->{      ...select(type == 'photo' => {          "image": {      "id": _id,  "alt": title,  "url": imageFile.asset->url,  "lqip": imageFile.asset->metadata.lqip,  "dimensions": imageFile.asset->metadata.dimensions  }      }),      ...select(type == 'video' => {          "video": {    "id": _id,    "alt": title,    "url": coalesce(videoUrl, videoFile.asset->url, externalUrl)  }      })    }}
export type EventsQueryResult = Array<{
  id: string;
  title: Array<{
    _type: "localeString";
    en?: string;
    pl?: string;
    ua?: string;
  }> | null;
  slug: Slug;
  date: string;
  tags: Array<{
    id: string;
    name: string;
  }>;
  media: {
    image: {
      id: string;
      alt: string;
      url: string | null;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    };
    video: {
      id: string;
      alt: string;
      url: string | null;
    };
  } | null;
}>;
// Variable: eventQuery
// Query: *[_type == "events" && slug.current == $slug][0]{  "id": _id,  "title": eventTitle[$locale],  "description": eventDescription[$locale],  date,  "tags": tags[]->{    "id": _id,    name  }}
export type EventQueryResult = {
  id: string;
  title: Array<{
    _type: "localeString";
    en?: string;
    pl?: string;
    ua?: string;
  }> | null;
  description: Array<{
    _type: "localeBlockContent";
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    pl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    ua?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }> | null;
  date: string;
  tags: Array<{
    id: string;
    name: string;
  }>;
} | null;
// Variable: eventMediaQuery
// Query: *[_type == "events" && slug.current == $slug][0]{  "media": media[]->{    ...select(type == 'photo' => {        "image": {      "id": _id,  "alt": title,  "url": imageFile.asset->url,  "lqip": imageFile.asset->metadata.lqip,  "dimensions": imageFile.asset->metadata.dimensions  }    }),    ...select(type == 'video' => {        "video": {    "id": _id,    "alt": title,    "url": coalesce(videoUrl, videoFile.asset->url, externalUrl)  }    })  }}
export type EventMediaQueryResult = {
  media: Array<{
    image: {
      id: string;
      alt: string;
      url: string | null;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    };
    video: {
      id: string;
      alt: string;
      url: string | null;
    };
  }> | null;
} | null;
// Variable: allEventsSlugsQuery
// Query: *[_type == "events" && defined(slug.current)]{ "slug": slug.current }
export type AllEventsSlugsQueryResult = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"media\" && type == \"photo\" && defined(imageFile.asset)] {\n    \n  \"image\": {\n    \n  \"id\": _id,\n  \"alt\": title,\n  \"url\": imageFile.asset->url,\n  \"lqip\": imageFile.asset->metadata.lqip,\n  \"dimensions\": imageFile.asset->metadata.dimensions\n\n  }\n\n  }\n": GalleryPhotosQueryResult;
    "*[_type == \"events\" && references(*[_type == \"tag\" && name == \"concert\"]._id) && date >= now()] {\n    \n  \"id\": _id,\n  \"title\": eventTitle[$locale],\n  date,\n  time,\n  \n  \"location\": location->{\n    place,\n    address,\n  }\n\n\n  }": FutureEventsQueryResult;
    "*[_type == \"events\" && references(*[_type == \"tag\" && name == \"concert\"]._id) && date < now()] | order(date desc) {\n    \n  \"id\": _id,\n  \"title\": eventTitle[$locale],\n  date,\n  time,\n  \n  \"location\": location->{\n    place,\n    address,\n  }\n\n\n  }": PastEventsQueryResult;
    "count(*[_type == \"media\" && type == \"photo\" && defined(imageFile.asset)])": GalleryPhotosCountQueryResult;
    "\n  *[_type == \"events\" && references(*[_type == \"tag\" && name == \"major\"]._id)] | order(date asc) {\n  \"id\": _id,\n  \"title\": eventTitle[$locale],\n  date,\n  \"media\": media[]->{\n    ...select(type == 'photo' => {\n      \n  \"image\": {\n    \n  \"id\": _id,\n  \"alt\": title,\n  \"url\": imageFile.asset->url,\n  \"lqip\": imageFile.asset->metadata.lqip,\n  \"dimensions\": imageFile.asset->metadata.dimensions\n\n  }\n\n    })\n  },\n  }\n": MajorEventsQueryResult;
    "\n  *[_type == \"events\" && references(*[_type == \"tag\" && name == \"minor\" || name == \"major\"]._id)] | order(date asc) {\n  \"id\": _id,\n  \"description\": eventDescription[$locale],\n  date,\n  \"media\": media[]->{\n    ...select(type == 'photo' => {\n      \n  \"image\": {\n    \n  \"id\": _id,\n  \"alt\": title,\n  \"url\": imageFile.asset->url,\n  \"lqip\": imageFile.asset->metadata.lqip,\n  \"dimensions\": imageFile.asset->metadata.dimensions\n\n  }\n\n    }),\n    ...select(type == 'video' => {\n      \n  \"video\": {\n    \"id\": _id,\n    \"alt\": title,\n    \"url\": coalesce(videoUrl, videoFile.asset->url, externalUrl)\n  }\n\n    })\n  },\n  }\n": MinorEventsQueryResult;
    "\n  *[_type == \"events\" && references(*[_type == \"tag\" && name == \"major\"]._id)] | order(date asc) {\n    date\n  }\n": MajorEventsYearsQueryResult;
    "count(*[_type == \"events\" && references(*[_type == \"tag\" && (name == \"major\" || name == \"minor\")]._id)])": EventsCountQueryResult;
    "\n  *[_type == \"events\" && references(*[_type == \"tag\" && (name == \"major\" || name == \"minor\")]._id)]\n  | order(date desc) [$start...$end] {\n    \"id\": _id,\n    \"title\": eventTitle[$locale],\n    slug,\n    date,\n    \"tags\": tags[]->{\n      \"id\": _id,\n      name\n    },\n    \"media\": media[0]->{\n      ...select(type == 'photo' => {\n        \n  \"image\": {\n    \n  \"id\": _id,\n  \"alt\": title,\n  \"url\": imageFile.asset->url,\n  \"lqip\": imageFile.asset->metadata.lqip,\n  \"dimensions\": imageFile.asset->metadata.dimensions\n\n  }\n\n      }),\n      ...select(type == 'video' => {\n        \n  \"video\": {\n    \"id\": _id,\n    \"alt\": title,\n    \"url\": coalesce(videoUrl, videoFile.asset->url, externalUrl)\n  }\n\n      })\n    }\n}": EventsQueryResult;
    "*[_type == \"events\" && slug.current == $slug][0]{\n  \"id\": _id,\n  \"title\": eventTitle[$locale],\n  \"description\": eventDescription[$locale],\n  date,\n  \"tags\": tags[]->{\n    \"id\": _id,\n    name\n  }\n}": EventQueryResult;
    "*[_type == \"events\" && slug.current == $slug][0]{\n  \"media\": media[]->{\n    ...select(type == 'photo' => {\n      \n  \"image\": {\n    \n  \"id\": _id,\n  \"alt\": title,\n  \"url\": imageFile.asset->url,\n  \"lqip\": imageFile.asset->metadata.lqip,\n  \"dimensions\": imageFile.asset->metadata.dimensions\n\n  }\n\n    }),\n    ...select(type == 'video' => {\n      \n  \"video\": {\n    \"id\": _id,\n    \"alt\": title,\n    \"url\": coalesce(videoUrl, videoFile.asset->url, externalUrl)\n  }\n\n    })\n  }\n}": EventMediaQueryResult;
    "*[_type == \"events\" && defined(slug.current)]{ \"slug\": slug.current }": AllEventsSlugsQueryResult;
  }
}
