/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Media = {
  _id: string;
  _type: "media";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  type: "photo" | "video" | "url";
  imageFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  videoUrl?: string;
  externalUrl?: string;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Events = {
  _id: string;
  _type: "events";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventTitle?: LocaleString;
  slug: Slug;
  eventDescription?: LocaleBlockContent;
  date: string;
  time?: string;
  location?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "location";
  };
  media?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "media";
  }>;
  tags: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "tag";
  }>;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  place: string;
  address: string;
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  pl?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ua?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type LocaleString = {
  _type: "localeString";
  en?: string;
  pl?: string;
  ua?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | Media
  | SanityFileAsset
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Events
  | Location
  | LocaleBlockContent
  | Slug
  | LocaleString
  | Tag;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: futureEventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date >= now()] {    _id,    "eventTitle": eventTitle[$locale],    date,    time,    "location": location->{      place,      address,    }  }
export type FutureEventsQueryResult = Array<{
  _id: string;
  eventTitle: string;
  date: string;
  time: string | null;
  location: {
    place: string;
    address: string;
  } | null;
}>;
// Variable: pastEventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date < now()] | order(date desc) {    _id,    "eventTitle": eventTitle[$locale],    date,    time,    "location": location->{      place,      address,    }  }
export type PastEventsQueryResult = Array<{
  _id: string;
  eventTitle: string;
  date: string;
  time: string | null;
  location: {
    place: string;
    address: string;
  } | null;
}>;
// Variable: futureEventsCountQuery
// Query: count(*[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date >= now()])
export type FutureEventsCountQueryResult = number;
// Variable: pastEventsCountQuery
// Query: count(*[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date < now()])
export type PastEventsCountQueryResult = number;
// Variable: galleryPhotosQuery
// Query: *[_type == "media" && type == "photo" && defined(imageFile.asset)] {    _id,    title,    "imageUrl": imageFile.asset->url,    "lqip": imageFile.asset->metadata.lqip,    "dimensions": imageFile.asset->metadata.dimensions  }
export type GalleryPhotosQueryResult = Array<{
  _id: string;
  title: string;
  imageUrl: string | null;
  lqip: string | null;
  dimensions: SanityImageDimensions | null;
}>;
// Variable: galleryPhotosCountQuery
// Query: count(*[_type == "media" && type == "photo" && defined(imageFile.asset)])
export type GalleryPhotosCountQueryResult = number;
// Variable: majorEventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "major"]._id)] | order(date asc) {    _id,    "eventTitle": eventTitle[$locale],    date,    "media": media[]->{      imageFile,      _id,      "imageUrl": imageFile.asset->url,      "lqip": imageFile.asset->metadata.lqip,      "dimensions": imageFile.asset->metadata.dimensions    }  }
export type MajorEventsQueryResult = Array<{
  _id: string;
  eventTitle: string;
  date: string;
  media: Array<{
    imageFile: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    _id: string;
    imageUrl: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  }> | null;
}>;
// Variable: majorEventsYearsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "major"]._id)] | order(date asc) {    date  }
export type MajorEventsYearsQueryResult = Array<{
  date: string;
}>;
// Variable: minorEventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && name == "minor" || name == "major"]._id)] | order(date asc) {    _id,    "eventTitle": eventTitle[$locale],    date,    "eventDescription": eventDescription[$locale],    "media": media[]->{      _id,      "imageUrl": imageFile.asset->url,      "lqip": imageFile.asset->metadata.lqip,      "dimensions": imageFile.asset->metadata.dimensions,      videoUrl,      imageFile    }  }
export type MinorEventsQueryResult = Array<{
  _id: string;
  title: string;
  date: string;
  eventDescription: Array<{
    _type: "localeBlockContent";
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    pl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    ua?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }> | null;
  media: Array<{
    _id: string;
    imageUrl: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
    videoUrl: string | null;
    imageFile: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
}>;
// Variable: eventsCountQuery
// Query: count(*[_type == "events" && references(*[_type == "tag" && (name == "major" || name == "minor")]._id)])
export type EventsCountQueryResult = number;
// Variable: eventsQuery
// Query: *[_type == "events" && references(*[_type == "tag" && (name == "major" || name == "minor")]._id)] | order(date desc) [$start...$end] {  _id,  "eventTitle": eventTitle[$locale],  slug,  date,  time,  location->{    title  },  "media": media[]->{    _id,    title,    type,    "imageUrl": imageFile.asset->url,    "lqip": imageFile.asset->metadata.lqip,    "dimensions": imageFile.asset->metadata.dimensions,    videoUrl,  },  tags[]->{    _id,    name  }}
export type EventsQueryResult = Array<{
  _id: string;
  eventTitle: string;
  slug: Slug;
  date: string;
  time: string | null;
  location: {
    title: null;
  } | null;
  media: Array<{
    _id: string;
    title: string;
    type: "photo" | "url" | "video";
    imageUrl: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
    videoUrl: string | null;
  }> | null;
  tags: Array<{
    _id: string;
    name: string;
  }>;
}>;
// Variable: eventQuery
// Query: *[_type == "events" && slug.current == $slug][0]{  _id,  "eventTitle": eventTitle[$locale],  "eventDescription": eventDescription[$locale],  date,  time,  location->{    title,    url  },  "media": media[]->{    _id,    title,    type,    "imageUrl": imageFile.asset->url,    "lqip": imageFile.asset->metadata.lqip,    "dimensions": imageFile.asset->metadata.dimensions,    videoUrl,  },  tags[]->{    _id,    name  }}
export type EventQueryResult = {
  _id: string;
  eventTitle: string;
  eventDescription: Array<{
    _type: "localeBlockContent";
    en?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    pl?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    ua?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }> | null;
  date: string;
  time: string | null;
  location: {
    title: null;
    url: null;
  } | null;
  media: Array<{
    _id: string;
    title: string;
    type: "photo" | "url" | "video";
    imageUrl: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
    videoUrl: string | null;
  }> | null;
  tags: Array<{
    _id: string;
    name: string;
  }>;
} | null;
// Variable: allEventsSlugsQuery
// Query: *[_type == "events" && defined(slug.current)]{ "slug": slug.current }
export type AllEventsSlugsQueryResult = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date >= now()] {\n    _id,\n    "eventTitle": eventTitle[$locale],\n    date,\n    time,\n    "location": location->{\n      place,\n      address,\n    }\n  }': FutureEventsQueryResult;
    '*[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date < now()] | order(date desc) {\n    _id,\n    "eventTitle": eventTitle[$locale],\n    date,\n    time,\n    "location": location->{\n      place,\n      address,\n    }\n  }': PastEventsQueryResult;
    'count(*[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date >= now()])': FutureEventsCountQueryResult;
    'count(*[_type == "events" && references(*[_type == "tag" && name == "concert"]._id) && date < now()])': PastEventsCountQueryResult;
    '\n  *[_type == "media" && type == "photo" && defined(imageFile.asset)] {\n    _id,\n    title,\n    "imageUrl": imageFile.asset->url,\n    "lqip": imageFile.asset->metadata.lqip,\n    "dimensions": imageFile.asset->metadata.dimensions\n  }\n': GalleryPhotosQueryResult;
    'count(*[_type == "media" && type == "photo" && defined(imageFile.asset)])': GalleryPhotosCountQueryResult;
    '\n  *[_type == "events" && references(*[_type == "tag" && name == "major"]._id)] | order(date asc) {\n    _id,\n    "eventTitle": eventTitle[$locale],\n    date,\n    "media": media[]->{\n      imageFile,\n      _id,\n      "imageUrl": imageFile.asset->url,\n      "lqip": imageFile.asset->metadata.lqip,\n      "dimensions": imageFile.asset->metadata.dimensions\n    }\n  }\n': MajorEventsQueryResult;
    '\n  *[_type == "events" && references(*[_type == "tag" && name == "major"]._id)] | order(date asc) {\n    date\n  }\n': MajorEventsYearsQueryResult;
    '\n  *[_type == "events" && references(*[_type == "tag" && name == "minor" || name == "major"]._id)] | order(date asc) {\n    _id,\n    "eventTitle": eventTitle[$locale],\n    date,\n    "eventDescription": eventDescription[$locale],\n    "media": media[]->{\n      _id,\n      "imageUrl": imageFile.asset->url,\n      "lqip": imageFile.asset->metadata.lqip,\n      "dimensions": imageFile.asset->metadata.dimensions,\n      videoUrl,\n      imageFile\n    }\n  }\n': MinorEventsQueryResult;
    'count(*[_type == "events" && references(*[_type == "tag" && (name == "major" || name == "minor")]._id)])': EventsCountQueryResult;
    '*[_type == "events" && references(*[_type == "tag" && (name == "major" || name == "minor")]._id)] | order(date desc) [$start...$end] {\n  _id,\n  "eventTitle": eventTitle[$locale],\n  slug,\n  date,\n  time,\n  location->{\n    title\n  },\n  "media": media[]->{\n    _id,\n    title,\n    type,\n    "imageUrl": imageFile.asset->url,\n    "lqip": imageFile.asset->metadata.lqip,\n    "dimensions": imageFile.asset->metadata.dimensions,\n    videoUrl,\n  },\n  tags[]->{\n    _id,\n    name\n  }\n}': EventsQueryResult;
    '*[_type == "events" && slug.current == $slug][0]{\n  _id,\n  "eventTitle": eventTitle[$locale],\n  "eventDescription": eventDescription[$locale],\n  date,\n  time,\n  location->{\n    title,\n    url\n  },\n  "media": media[]->{\n    _id,\n    title,\n    type,\n    "imageUrl": imageFile.asset->url,\n    "lqip": imageFile.asset->metadata.lqip,\n    "dimensions": imageFile.asset->metadata.dimensions,\n    videoUrl,\n  },\n  tags[]->{\n    _id,\n    name\n  }\n}': EventQueryResult;
    '*[_type == "events" && defined(slug.current)]{ "slug": slug.current }': AllEventsSlugsQueryResult;
  }
}
